export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES"
export const SEARCH_COUNTRY_NAME = "SEARCH_COUNTRY_NAME"
export const FILTER_COUNTRY_REGION = "FILTER_COUNTRY_REGION"
export const SWITCH_THEME = "SWITCH_THEME"